# Generated by Django 4.1.7 on 2023-10-20 10:51

from django.db import migrations, models
import tasks.validator


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(validators=[tasks.validator.validate_age])),
            ],
        ),
    ]
