# Generated by Django 4.2.4 on 2023-10-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_hotelroom_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroom',
            old_name='is_reversed',
            new_name='is_reserved',
        ),
    ]
