# Generated by Django 4.2.6 on 2023-10-22 10:02
import random

from django.db import migrations


def add_barcode(app, schema_editor):
    Product = app.get_model("main_app", "Product")
    all_products = Product.objects.all()
    all_barcodes = random.sample(
        range(100000000, 100000000),
        len(all_products))

    print(all_barcodes)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0004_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.RunPython(add_barcode),
    ]
