# Generated by Django 4.2.4 on 2023-10-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shoe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
