# Generated by Django 4.2.6 on 2023-10-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='name',
        ),
        migrations.AddField(
            model_name='mybook',
            name='auth',
            field=models.TextField(default='Stephen King', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='mybook',
            name='fist_name',
            field=models.CharField(default='Ivan', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='mybook',
            name='genre',
            field=models.CharField(choices=[('Stephen King', 'Stephen King'), ('Dan Brown', 'Dan Brown'), ('James Patterson', 'James Patterson'), ('Leo Tolstoy', 'Leo Tolstoy'), ('John Grisham', 'John Grisham')], default='Stephen King', max_length=40),
        ),
        migrations.AddField(
            model_name='mybook',
            name='last_name',
            field=models.CharField(default='Ivanov', max_length=10, unique=True),
        ),
    ]
